services:
  postgres:
    image: postgres:17
    container_name: customerapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HapTest@28

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: customerapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customerapi_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://customerapi_db:5432/customerDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: HapTest@28
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      - postgres


volumes:
  postgres_data:
